-- Checkpoint questions and track-tagged exercises for the learner-setup test course.
-- Only fills sections that have no questions/exercises yet, so authored content is never overwritten.
UPDATE courses SET curriculum = jsonb_set(curriculum, '{0,quiz}', $json$[{"prompt":"What is the main outcome you build across this course?","options":["A style guide","A portfolio-ready UX case study","A coded prototype","A marketing site"],"answer":1,"explanation":"Every section feeds the case study."},{"prompt":"In the UX process taught here, what comes first?","options":["Wireframing","Visual design","User research","Handoff"],"answer":2,"explanation":""},{"prompt":"Which tool do you set up in section 1?","options":["Sketch","Figma","Framer","Illustrator"],"answer":1,"explanation":""},{"prompt":"Why start from a case study brief?","options":["It replaces research","It gives every exercise a real context","It's required by Figma","It shortens the course"],"answer":1,"explanation":""}]$json$::jsonb, true)
 WHERE title = 'UX Foundations: Research to Wireframe' AND jsonb_array_length(curriculum) > 0 AND coalesce(jsonb_array_length(curriculum->0->'quiz'), 0) = 0;
UPDATE courses SET curriculum = jsonb_set(curriculum, '{0,exercises}', $json$[{"track":"job_ready","title":"Write a one-page project brief","body":"Draft a brief for a real product you'd like in your portfolio: problem, audience, success metric, constraints. Aim for something a stakeholder could sign off."},{"track":"project","title":"Pick your case-study product","body":"Choose one product idea and write three sentences: who it's for, what it does, what 'done' looks like for this course. Keep it small enough to finish."},{"track":"exploring","title":"Map the UX process","body":"In your own words, list the stages of the UX process from the lesson and one question you have about each."}]$json$::jsonb, true)
 WHERE title = 'UX Foundations: Research to Wireframe' AND jsonb_array_length(curriculum) > 0 AND coalesce(jsonb_array_length(curriculum->0->'exercises'), 0) = 0;
UPDATE courses SET curriculum = jsonb_set(curriculum, '{1,quiz}', $json$[{"prompt":"What makes a good interview question?","options":["It suggests the answer you want","It asks about past behaviour, not hypotheticals","It's a yes/no question","It's about the competitor"],"answer":1,"explanation":"Ask what people did, not what they would do."},{"prompt":"How many interviews does the course suggest for a lightweight study?","options":["1–2","5–8","50+","As many as possible"],"answer":1,"explanation":""},{"prompt":"What is the goal of synthesis?","options":["To transcribe everything","To turn notes into patterns and insights","To pick the best participant","To write the final report"],"answer":1,"explanation":""},{"prompt":"A research plan should state:","options":["Only the questions","Goal, participants, method and what you'll decide","The wireframes","The brand colours"],"answer":1,"explanation":""}]$json$::jsonb, true)
 WHERE title = 'UX Foundations: Research to Wireframe' AND jsonb_array_length(curriculum) > 1 AND coalesce(jsonb_array_length(curriculum->1->'quiz'), 0) = 0;
UPDATE courses SET curriculum = jsonb_set(curriculum, '{1,exercises}', $json$[{"track":"job_ready","title":"Run two real interviews","body":"Recruit two people from your target audience, run 20-minute interviews with your script, and write a one-page synthesis with three insights and the evidence for each."},{"track":"project","title":"Interview one person","body":"Run a single 15-minute interview about your product idea and capture the three most surprising things you heard."},{"track":"exploring","title":"Critique an interview script","body":"Take the sample script from the lesson and mark every leading or hypothetical question. Rewrite two of them."}]$json$::jsonb, true)
 WHERE title = 'UX Foundations: Research to Wireframe' AND jsonb_array_length(curriculum) > 1 AND coalesce(jsonb_array_length(curriculum->1->'exercises'), 0) = 0;
UPDATE courses SET curriculum = jsonb_set(curriculum, '{2,quiz}', $json$[{"prompt":"Card sorting helps you discover:","options":["Colour preferences","How users group and label content","Which font to use","Server structure"],"answer":1,"explanation":""},{"prompt":"A sitemap shows:","options":["The visual style","The hierarchy of pages/screens","The database schema","The team structure"],"answer":1,"explanation":""},{"prompt":"A user flow answers:","options":["What the page looks like","The steps a user takes to reach a goal","Who the stakeholders are","How much it costs"],"answer":1,"explanation":""},{"prompt":"How do you validate an IA before wireframing?","options":["Ship it","Tree testing or a quick task test with users","Ask the CEO","Pick the shortest sitemap"],"answer":1,"explanation":""}]$json$::jsonb, true)
 WHERE title = 'UX Foundations: Research to Wireframe' AND jsonb_array_length(curriculum) > 2 AND coalesce(jsonb_array_length(curriculum->2->'quiz'), 0) = 0;
UPDATE courses SET curriculum = jsonb_set(curriculum, '{2,exercises}', $json$[{"track":"job_ready","title":"Sitemap + two validated flows","body":"Produce a sitemap for your product and two key user flows. Test them with two people using tree-testing style tasks and note what you changed."},{"track":"project","title":"Sketch the sitemap","body":"Draw your product's sitemap on one page and the single most important user flow, start to goal."},{"track":"exploring","title":"Reverse-engineer an IA","body":"Pick an app you use daily and sketch its sitemap from memory. Where does its structure surprise you?"}]$json$::jsonb, true)
 WHERE title = 'UX Foundations: Research to Wireframe' AND jsonb_array_length(curriculum) > 2 AND coalesce(jsonb_array_length(curriculum->2->'exercises'), 0) = 0;
UPDATE courses SET curriculum = jsonb_set(curriculum, '{3,quiz}', $json$[{"prompt":"Why sketch low-fidelity first?","options":["Stakeholders prefer it","It's cheap to explore many layouts before committing","Figma requires it","It looks finished"],"answer":1,"explanation":""},{"prompt":"A responsive wireframe should show:","options":["Only desktop","Key breakpoints and how content reflows","Final colours","Animations"],"answer":1,"explanation":""},{"prompt":"What makes a wireframe handoff-ready?","options":["Pixel-perfect visuals","Annotated states, flows and edge cases a developer can build from","A PDF export","A logo"],"answer":1,"explanation":""},{"prompt":"Which of these belongs in wireframe annotations?","options":["Brand tagline","What happens on error and empty states","Marketing copy","Font licensing"],"answer":1,"explanation":""}]$json$::jsonb, true)
 WHERE title = 'UX Foundations: Research to Wireframe' AND jsonb_array_length(curriculum) > 3 AND coalesce(jsonb_array_length(curriculum->3->'quiz'), 0) = 0;
UPDATE courses SET curriculum = jsonb_set(curriculum, '{3,exercises}', $json$[{"track":"job_ready","title":"Handoff-ready wireframes","body":"Wireframe the two key flows at mobile and desktop, annotate states and edge cases, and share a Figma link a developer could build from. Add it to your case study."},{"track":"project","title":"Wireframe the happy path","body":"Wireframe the main flow of your product at one breakpoint and mark the three screens you'd build first."},{"track":"exploring","title":"Annotate an existing screen","body":"Take a screenshot of any app screen and annotate its states: loading, empty, error, success."}]$json$::jsonb, true)
 WHERE title = 'UX Foundations: Research to Wireframe' AND jsonb_array_length(curriculum) > 3 AND coalesce(jsonb_array_length(curriculum->3->'exercises'), 0) = 0;
